#!/usr/bin/env python3
"""
harness_boot.py — Agent framework startup bootstrap script

Functions:
1. Initialize the workspace from templates (first run)
2. Verify all required files exist
3. Read mission.md and heartbeat.md, output current status summary
4. Called by Agent as the first step on each cron trigger

Usage:
    python3 harness_boot.py /path/to/workspace [--init]

Arguments:
    workspace_dir   Path to the workspace directory
    --init          First-time initialization: copy files from templates to workspace
"""

import argparse
import shutil
import sys
import os
import re
from datetime import datetime
from pathlib import Path


# Framework template directory (relative to this script)
SCRIPT_DIR = Path(__file__).parent.resolve()
TEMPLATE_DIR = SCRIPT_DIR.parent / "templates"

# Required files list
REQUIRED_FILES = [
    "mission.md",
    "playbook.md",
    "heartbeat.md",
    "progress.md",
    "eval_criteria.md",
    "cron_config.md",
]

# Files copied from templates on --init (heartbeat.md and progress.md are generated by Agent based on mission content, not copied from templates)
TEMPLATE_COPY_FILES = ["mission.md", "playbook.md", "eval_criteria.md", "cron_config.md"]

# Files that Agent requires user to fill (must not contain placeholders)
USER_FILL_FILES = ["mission.md", "playbook.md", "eval_criteria.md", "cron_config.md"]


def init_workspace(workspace: Path):
    """Initialize workspace from templates"""
    workspace.mkdir(parents=True, exist_ok=True)

    # Create output directories
    (workspace / "output").mkdir(exist_ok=True)
    (workspace / "logs").mkdir(exist_ok=True)

    copied = []
    skipped = []
    for fname in TEMPLATE_COPY_FILES:
        src = TEMPLATE_DIR / fname
        dst = workspace / fname
        if dst.exists():
            skipped.append(fname)
        elif src.exists():
            shutil.copy2(src, dst)
            copied.append(fname)
        else:
            print(f"[WARN] Template file does not exist: {src}")

    print(f"[BOOT] Workspace initialized: {workspace}")
    print(f"  Copied {len(copied)} structure templates: {', '.join(copied)}")
    if skipped:
        print(f"  Skipped {len(skipped)} existing files: {', '.join(skipped)}")
    print(f"  Output directory: {workspace / 'output'}")
    print(f"  Logs directory: {workspace / 'logs'}")
    print()
    print("[NEXT] Agent needs to complete the following:")
    print(f"  ✏️  Fill in according to mission content: {workspace}/mission.md")
    print(f"  ✏️  Fill in according to mission content: {workspace}/playbook.md")
    print(f"  ✏️  Fill in according to mission content: {workspace}/eval_criteria.md")
    print(f"  ✏️  Fill in according to mission content: {workspace}/cron_config.md")
    print(f"  ✏️  Generate by yourself (not copied from template): {workspace}/heartbeat.md")
    print(f"  ✏️  Generate by yourself (not copied from template): {workspace}/progress.md")


def _is_filled(filepath: Path) -> bool:
    """Check if the file has been filled by the user (no longer contains placeholders)"""
    if not filepath.exists():
        return False
    content = filepath.read_text(encoding="utf-8")
    # Check if there are still unfilled placeholders
    return "[Fill in" not in content and "[e.g.," not in content


def validate_workspace(workspace: Path) -> dict:
    """Validate workspace integrity, return status report"""
    report = {
        "workspace": str(workspace),
        "exists": workspace.exists(),
        "files": {},
        "ready": True,
        "issues": [],
    }

    if not workspace.exists():
        report["ready"] = False
        report["issues"].append(f"Workspace does not exist: {workspace}")
        return report

    for fname in REQUIRED_FILES:
        fpath = workspace / fname
        finfo = {
            "exists": fpath.exists(),
            "filled": _is_filled(fpath) if fpath.exists() else False,
            "size": fpath.stat().st_size if fpath.exists() else 0,
        }
        report["files"][fname] = finfo

        if not finfo["exists"]:
            report["ready"] = False
            report["issues"].append(f"Missing file: {fname}")
        elif fname in USER_FILL_FILES and not finfo["filled"]:
            # heartbeat.md and progress.md are generated by Agent itself, no placeholder check
            report["ready"] = False
            report["issues"].append(f"File not filled: {fname} (still contains placeholders)")

    return report


def read_heartbeat(workspace: Path) -> dict:
    """Read heartbeat.md and parse current status
    
    Important: heartbeat.md must be in the workspace root directory, i.e. {workspace}/heartbeat.md.
    It must not be placed in subdirectories or other locations.
    """
    hb_path = workspace / "heartbeat.md"
    if not hb_path.exists():
        return {"status": "no_heartbeat", "message": "heartbeat.md does not exist"}

    content = hb_path.read_text(encoding="utf-8")

    # Parse key fields
    status_match = re.search(r"\| Current Status \| `(.+?)`", content)
    step_match = re.search(r"\| Current Step \| `(.+?)`", content)
    last_time_match = re.search(r"\| Last Execution Time \| `(.+?)`", content)
    fail_match = re.search(r"\| Consecutive Failures \| `(\d+)`", content)
    total_match = re.search(r"\| Total Executions \| `(\d+)`", content)

    return {
        "status": status_match.group(1) if status_match else "unknown",
        "current_step": step_match.group(1) if step_match else "unknown",
        "last_execution": last_time_match.group(1) if last_time_match else "unknown",
        "consecutive_failures": int(fail_match.group(1)) if fail_match else 0,
        "total_executions": int(total_match.group(1)) if total_match else 0,
    }


def read_mission_name(workspace: Path) -> str:
    """Read mission name from mission.md"""
    mission_path = workspace / "mission.md"
    if not mission_path.exists():
        return "[Undefined]"
    content = mission_path.read_text(encoding="utf-8")
    name_match = re.search(r"\*\*Name\*\*[：:]\s*`(.+?)`", content)
    return name_match.group(1) if name_match else "[Not filled]"


def boot_report(workspace: Path):
    """Generate startup report"""
    print("=" * 60)
    print("  Agent Framework (Harness-24h) — Startup Report")
    print(f"  Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)

    # Validate workspace
    validation = validate_workspace(workspace)
    mission_name = read_mission_name(workspace)
    heartbeat = read_heartbeat(workspace)

    print(f"\n📋 Mission: {mission_name}")
    print(f"📁 Workspace: {workspace}")
    print(f"💓 Status: {heartbeat.get('status', 'unknown')}")
    print(f"📍 Current Step: {heartbeat.get('current_step', 'unknown')}")
    print(f"🔄 Total Executions: {heartbeat.get('total_executions', 0)}")
    print(f"❌ Consecutive Failures: {heartbeat.get('consecutive_failures', 0)}")
    print(f"🕐 Last Execution: {heartbeat.get('last_execution', 'unknown')}")

    if validation["issues"]:
        print(f"\n⚠️  Found {len(validation['issues'])} issues:")
        for issue in validation["issues"]:
            print(f"  - {issue}")

    if validation["ready"]:
        print("\n✅ Workspace is ready, execution can start.")
    else:
        print("\n❌ Workspace is not ready, please resolve the above issues first.")

    # Check if upgrade is needed (too many consecutive failures)
    if heartbeat.get("consecutive_failures", 0) >= 3:
        print("\n🚨 Warning: More than 3 consecutive failures, manual intervention recommended!")

    if heartbeat.get("status") == "mission_complete":
        print("\n🎉 Mission completed! No further execution needed.")

    print("=" * 60)
    return validation["ready"]


def main():
    parser = argparse.ArgumentParser(description="Agent Framework Startup Bootstrap")
    parser.add_argument("workspace", help="Path to workspace directory")
    parser.add_argument("--init", action="store_true", help="Initialize workspace for the first time")
    args = parser.parse_args()

    workspace = Path(args.workspace).resolve()

    if args.init:
        init_workspace(workspace)
    else:
        ready = boot_report(workspace)
        sys.exit(0 if ready else 1)


if __name__ == "__main__":
    main()
